---
title: "Projet - 4surX - ACP et AFD"
author: "Nicolas SALVAN"
date: "2024-05-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lecture des données nettoyées 

## Importation du dataset 

```{r}
data <- read.csv("data/data_cleaned.csv", header = TRUE, sep = ",")
data$diagnosis <- as.factor(data$diagnosis)

train_data <- read.csv("data/train_data.csv", header = TRUE, sep = ",")
train_data$diagnosis <- as.factor(train_data$diagnosis)

test_data <- read.csv("data/test_data.csv", header = TRUE, sep = ",")
test_data$diagnosis <- as.factor(test_data$diagnosis)
```

## Aperçu rapide 

```{r}
head(data)
# dim(data)
# str(data)
```

# AFD - Analyse Factorielle discriminante 

## Lancement d'une AFD sur les données d'entraînement 

```{r}
library(MASS)
```


```{r}
res.afd <- lda(diagnosis ~ ., data = data)
res.afd
```


```{r}
plot(res.afd)
```

```{r}
library("FactoMineR")
```

```{r}

```

```{r}
plot(res.afd, choix="var")
```

```{r}
plot(res.afd, choix="ind")
```

```{r}
```


