---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lecture des données nettoyées 

## Importation du dataset 

```{r}
data <- read.csv("data/data_cleaned.csv", header = TRUE, sep = ",")
data$diagnosis <- as.factor(data$diagnosis)

train_data <- read.csv("data/train_data.csv", header = TRUE, sep = ",")
train_data$diagnosis <- as.factor(train_data$diagnosis)

test_data <- read.csv("data/test_data.csv", header = TRUE, sep = ",")
test_data$diagnosis <- as.factor(test_data$diagnosis)
```


```{r}
attach(train_data)
```


# CART

```{r}
library(rpart)
arbre = rpart(diagnosis~., train_data)
```


```{r}
print(arbre)
```

```{r}
library(rpart.plot)
```

```{r}
rpart.plot(arbre, type=4, digits=3,roundint=FALSE)
```

```{r}
arbre2=rpart(diagnosis~.,train_data,control=rpart.control(minsplit=5))
rpart.plot(arbre2, type=4, digits=3)
```
## elagage

```{r}
arbre=rpart(diagnosis~.,train_data,control=rpart.control(minsplit=5,cp=0))
rpart.plot(arbre, type=4)
```

```{r}
plotcp(arbre)
```
cp minimal en 4 ou en 7

```{r}
cp.opt <- arbre$cptable[which.min(arbre$cptable[, "xerror"]), "CP"]
arbre.opt <- prune(arbre,cp=cp.opt)
rpart.plot(arbre.opt, type=4)
```

## prediction

```{r}
pred= predict(arbre.opt, newdata=test_data, type="prob")
head(pred)
```

```{r}
pred= predict(arbre.opt, newdata=test_data, type="class")
head(pred)
```

