---
title: "Untitled"
author: "Alexandre CORRIOU, Nicolas SALVAN"
date: "2024-05-24"
output: html_document
---

# Lecture des données nettoyées 

## Importation du dataset 

```{r}
data <- read.csv("data/data_cleaned.csv", header = TRUE, sep = ",")
data$diagnosis <- as.factor(data$diagnosis)
```

# Classification non-supervisée

## Dendrogramme

```{r}
data.clust <- data[-1] #suppression des classes
data.cent <- scale(data.clust)
d.data = dist(data.cent)
hc <- hclust(d.data, method = "ward.D2")
plot(hc)
```
```{r}
barplot(hc$height[(dim(data)[1]-20):dim(data)[1]])
```
Selon les interprétations, on peut considérer qu'il faut garder deux ou trois classes.

```{r}
library(FactoMineR)
library(factoextra)
```
### Clustering à 3 groupes

```{r}
kmeans.result=kmeans(data.clust, nstart = 100, centers=3)
data_classe <- cbind.data.frame(data.clust, classe=factor(kmeans.result$cluster))
res <- PCA(data_classe, quali.sup = c(2,31), scale.unit = TRUE)
```
On remarque que beaucoup de variables sont très corrélées entre elles.

